/* -------------------------------------------------------------------------- */
/*                                   import                                   */
/* -------------------------------------------------------------------------- */

import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import SideBarL from '../../components/SideBarL';
import Presentation from '../../components/Presentation';
import ProductCartList from '../../layouts/ProductCartList';
import { useDispatch, useSelector } from 'react-redux';

/* -------------------------------------------------------------------------- */
/*                                    react                                   */
/* -------------------------------------------------------------------------- */

export default function Home() {
  return (
    <div className='flex flex-col max-w-[1420px] m-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Presentation />
      </header>

      <main className='flex flex-row  justify-between relative bottom-36  bg-gradient-to-r from-slate-900  to-cyan-900 text-stone-10 sm:rounded-3xl '>
        <SideBarL />
        <ProductCartList />
      </main>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*                      Communication avec serveur getServerSideProps         */
/* -------------------------------------------------------------------------- */

export async function getServerSideProps(ctx) {
  return {
    props: {
      data: null,
    },
  };
}
