/* -------------------------------------------------------------------------- */
/*                                   import                                   */
/* -------------------------------------------------------------------------- */

import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { setEventSlideL, reSetEventSlideL } from '../redux/featureData';
import Announce from '../components/Announce';

import NavBar from '../components/NavBar';
import SideBarL from '../components/SideBarL';
import Slide from '../components/Slide';
import MainSection from '../layouts/MainSection';
import ProductCartList from '../layouts/ProductCartList';
import { Link } from 'next/link';
import PromoCart from '../components/PromoCart';
import ProductCart from '../components/ProductCart';
/* -------------------------------------------------------------------------- */
/*                                    react                                   */
/* -------------------------------------------------------------------------- */

export default function Home() {
  //state.DataSliceL.eventSlideL

  return (
    <div className="flex flex-col  w-[99.9%]">
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="">
        <Announce />
        <Slide />
      </header>

      <main className="flex flex-col  justify-around  w-[99.9%] items-center ">
        {/* <SideBarL /> */}

        <div className="flex flex-row flex-wrap justify-around w-[99.9%] section bg-gradient-to-r from-slate-900  to-cyan-900 pt-3 mb-4 overflow-y-scroll promoCartTop sm:h-auto ">
          <PromoCart />
          <PromoCart />
          <PromoCart />
          <PromoCart />
        </div>

        <div className="flex flex-row flex-wrap  justify-around overflow-y-scroll  w-[99%] section bg-gradient-to-r from-cyan-700  to-cyan-800  pt-3 mb-4 ">
          <PromoCart />
          <PromoCart />
          <PromoCart />
          <PromoCart />
          <PromoCart />
        </div>
      </main>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*                      Communication avec serveur getServerSideProps         */
/* -------------------------------------------------------------------------- */

export async function getServerSideProps(ctx) {
  return {
    props: {
      data: null,
    },
  };
}
